[build]
builder = "nixpacks"

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311Full", "git"]

[phases.install]
cmds = [
  "cd backend", 
  "python3.11 -m ensurepip", 
  "python3.11 -m pip install --upgrade pip", 
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python3.11 server.py"
